image: mephux/docker-golang
branches:
  - master
  - develop
git:
  path: github.com/recruit2class/codetainer
script:
  - make
  - make test
notify:
  email:
    recipients:
      - dustin.webber@gmail.com
      - jandre@gmail.com
